### ISSUE TITLE
Howto get the it to run?

### ISSUE THREAD

**Issue by thor-n** [fritsvt/laravel-nuxt-authentication#1]
Hi

I have cloned the project, but cant get it to run.

I have done:

1. edit .env file

2. php artisan migrate:fresh --seed

3. Root: composer install and npm install

4 /Client: npm install

5. "npm run dev" in root "DONE  Compiled successfully in 6896ms" but it dont start server

6. "npm run dev" in /client

> jwt-auth@1.0.0 dev C:\wamp64\www\laravel-nuxt-authentication\client
> nuxt

'nuxt' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jwt-auth@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jwt-auth@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ddd\AppData\Roaming\npm-cache\_logs\2019-04-10T09_13_19_707Z-debug.log

**Comment by fritsvt** [comment]
Did you manage solve this already? If you've ran `npm install` in the client folder i'm not entirely sure what the error could be.
