### ISSUE TITLE
ERROR: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by adavie1** [fritsvt/laravel-nuxt-authentication#5]
After setting up Nuxt, etc. When running `npm run dev`, I get this error during server build.
I've also reported this error at `bugs.nuxtjs.org`

**Comment by adavie1** [comment]
The team at Nuxt suggest this fix:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Which worked for me on Ubuntu 18.04.

More details [here](https://github.com/nuxt/nuxt.js/issues/6172).

**Comment by tmnsit** [comment]
it work+
