### ISSUE TITLE
Twitter login does not work

### ISSUE THREAD

**Issue by connecteev** [fritsvt/laravel-nuxt-authentication#9]
I just submitted a PR to add the buttons and config for twitter and linkedin logins.
Linkedin works fine, but twitter does not.

This is the error I get when I try to log in with Twitter:

From /Code/laravel-nuxt-authentication/app/Http/Controllers/api/Auth/SocialLoginController.php

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Laravel\Socialite\One\TwitterProvider::stateless()
```

**Comment by fritsvt** [comment]
Merged in #7

**Comment by connecteev** [comment]
This still doesnt work.

**Comment by fritsvt** [comment]
Sadly I'm banned from creating new Twitter apps so I can't easily test my fix. (they didn't like a bot I had). But I'm pushing a change that should fix this.

**Comment by fritsvt** [comment]
https://github.com/fritsvt/laravel-nuxt-authentication/commit/8b3330e0388a54c30503609f278db88f3fe3b935 should fix it

**Comment by connecteev** [comment]
This would work but in my case, I have emojis in my twitter handle and see this error:
https://prnt.sc/ora282

```
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA7\xA0 K...' for column 'name' at row 1 (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (🧠 My Twitter 🧠🔥💥, 102033        2783931266511@twitter.local, , 2019-08-11 17:04:48, 2019-08-11 17:04:48))
Previous exceptions
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\xA7\xA0 K...' for column 'name' at row 1 (HY000)
```

**Comment by connecteev** [comment]
submitted a PR, everything works well now.
